---

- name: install common dev tools & packages
  become: true
  apt:
    pkg:    
      - awscli
      - curl
      - git
      - openjdk-11-jre-headless
      - tig
      - tree
      - unzip
      - zip

